### ISSUE TITLE
tiny README glitch: package is lsb-release; command is lsb_release

### ISSUE THREAD

**Issue by nonbob** [arkane-systems/wsl-transdebian#10]
I believe 
`apt install lsb_release`
should be
`apt install lsb-release`

I suppose I could submit a pull request for this but. . .would you rather change one character or field a pull request :-)

BTW, thanks so much for genie.  It enabled me to install the command line version of Docker on WSL-2 at work (for non-production usage on my desktop, now that the license terms on Docker Desktop have changed)

**Comment by cerebrate** [comment]
Thanks for pointing this out. Fixed now.
