### ISSUE TITLE
doesn't work on ubuntu-21.04 hirsute, missing release file

### ISSUE THREAD

**Issue by codemonkey76** [arkane-systems/wsl-transdebian#11]
doesn't work on ubuntu-21.04 hirsute, missing release file

**Comment by cerebrate** [comment]
We only officially support the Ubuntu LTS releases, since I have limited time and resources available to test on distributions I don't myself use. For _hirsute_, I suggest installing the _focal_ release by manually editing the created `sources.list` file, per instructions in the README.
