### ISSUE TITLE
Support for Ubuntu 22.04 LTS?

### ISSUE THREAD

**Issue by RowanSkie** [arkane-systems/wsl-transdebian#13]
Hey, I've been trying to install this to my Ubuntu WSL in an attempt to get myself a GUI (for personal reasons), and I realized that I can't really use this to install genie.

What's the risk for installing it anyway?

**Comment by RowanSkie** [comment]
Closing, I may have accidentally turned my LTS to latest development, whoops.

**Comment by cerebrate** [comment]
No worries.

Anyway, for what it's worth, the only risk is that since I use Debian myself and only have so much time, I've only tested it on the official Ubuntu LTS versions. So, y'know, it _ought_ to work, but if it doesn't...
