### ISSUE TITLE
-bash: /etc/apt/sources.list.d/wsl-transdebian.list: Permission denied

### ISSUE THREAD

**Issue by yahya-mohammed07** [arkane-systems/wsl-transdebian#19]
USING UBUNTU: 22.04.1

writing these commands gave me:  -bash: /etc/apt/sources.list.d/wsl-transdebian.list: Permission denied #19 

sudo -s chmod a+r /etc/apt/trusted.gpg.d/wsl-transdebian.gpg
sudo -s cat << EOF > /etc/apt/sources.list.d/wsl-transdebian.list
> deb https://arkane-systems.github.io/wsl-transdebian/apt/ $(lsb_release -cs) main
> deb-src https://arkane-systems.github.io/wsl-transdebian/apt/ $(lsb_release -cs) main
> EOF
-bash: /etc/apt/sources.list.d/wsl-transdebian.list: Permission denied

**Comment by cerebrate** [comment]
You should be running `sudo -s` once to get a root shell before running the listed commands, not prefixing it to them.
