### ISSUE TITLE
Dynamically generate snippet for supported distros

### ISSUE THREAD

**Issue by paramsiddharth** [arkane-systems/wsl-transdebian#2]
# Dynamically generate snippet for supported distros
Currently, the provided snippet contains `<distro>` that needs to manually be replaced upon execution with one of the above-mentioned distros.

![image](https://user-images.githubusercontent.com/30315706/113500633-31718900-953d-11eb-9137-69a736c02468.png)

To improve it significantly, we can instead use JavaScript and add a dropdown from where the user can select any of the supported distros and the respective snippet will be generated. We may also add a button, clicking which will directly copy the snippet to the clipboard (with the terminating newline).

I would like to work on this issue if approved.

**Comment by cerebrate** [comment]
Absolutely, it's a great idea. I'm not much of a web programmer myself, but if you'd like to work on it and send me a PR, I'd welcome it.

**Comment by paramsiddharth** [comment]
> Absolutely, it's a great idea. I'm not much of a web programmer myself, but if you'd like to work on it and send me a PR, I'd welcome it.

OK, Alistair! I will do it and make a PR.

**Comment by paramsiddharth** [comment]
@cerebrate I think the issue isn't relevant after 9696657ba2257949c5be906bf78879c76fd9001d, am I right? I think using `lsb_release` is the most reliable and straightforward way to implement this.

**Comment by cerebrate** [comment]
@paramsiddharth Sorry not to get back to you sooner; yes, I think you're right. Thanks for the offer, though - still much appreciated.
