### ISSUE TITLE
Add support for Ubuntu hirsute

### ISSUE THREAD

**Issue by SuperSandro2000** [arkane-systems/wsl-transdebian#8]

**Comment by cerebrate** [comment]
I'm not going to have time to check this myself for a while. Do me a favor - force-install the current .deb on hirsute and let me know if it works?

**Comment by cerebrate** [comment]
Ignore now-deleted last. Wrong repo.

**Comment by cerebrate** [comment]
To clarify: where "official" Ubuntu support is concerned - "official" as in, I tested this before I shipped it - I've had an unofficial policy of supporting those releases (thus far just the LTS releases) that show up in the Microsoft Store thus far on the grounds that I have only so much time to spend testing releases I don't use, in-between release users who know what they're doing can tweak the sources.list file themselves, and by doing so they confirm that this is not-tested-on-their-release.

Is there a particular reason for hirsute to be an exception to this?

**Comment by SuperSandro2000** [comment]
> in-between release users who know what they're doing can tweak the sources.list file themselves

That is exactly what I did.

> Is there a particular reason for hirsute to be an exception to this?

It would be easier to install. I don't think anything in hirsuite changed that breaks genie.

**Comment by sydelcid** [comment]
Any updates here? I'm getting the same issue, no Release file found for hirsute.

**Comment by SuperSandro2000** [comment]
Change hirsuite to focal in your sources.list.

**Comment by cerebrate** [comment]
Yeah, on thinking about it, I'm only going to officially support the most recent two Ubuntu LTS distributions. I don't have time to test against all of the various others as well as the Debian distros.

This is not, of course, to say that genie or any other package here won't work on hirsute or any other in-between Ubuntu distribution or other Debian derivative; merely that not having tested it myself, I'm not going to advertise that it _does_ by shipping a package entailed to that distribution.

Requiring the manual change of the sources.list reminds people of that.

(I'll be adding a clarifying note to this effect to the documentation.)

**Comment by sydelcid** [comment]
> Change hirsuite to focal in your sources.list.

Thanks, seems to work!
